[package]
name = "demo_shader_editor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["rlib"]

[[bin]]
name = "shader_editor"
path = "src/main.rs"
doc = false

[dependencies]
demo_common.workspace = true
iced = { workspace = true, features = ["wgpu", "crisp", "thread-pool", "linux-theme-detection", "x11", "wayland"] }
iced_nodegraph.workspace = true
iced_palette.workspace = true
